### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by Rywokast** [cholan2100/ceasar#1]
bluetooth does not work..

**Comment by cholan2100** [comment]
i remember the app needs LOCATION permission for Bluetooth BLE to work. Probably have to allow the permission manually in Android settings. This app is a quick hack, not as user friendly as it could be.

**Comment by Rywokast** [comment]
its very weird, because the app works fine.. i got it working with your code specifically https://github.com/cholan2100/SpotMicro_ESP32/tree/master/code/esp-idf/ik_test but i cannot get it to work with the "caesar" code... my phone doesnt even pick up bluetooth at all from the esp32 when using the caesar code... works fine with any other set of code ive tried.. i even tried overwriting the bluetooth filed in the code from a known set of working code O.o

**Comment by cholan2100** [comment]
Double check if the Ceasar project framework in ESP32 IDE environment does include Bluetooth BLE framework.

**Comment by cholan2100** [comment]
Hold on, i think the bluetooth comms part is disabled //#define BLUETOOTH_ENABLED in Ceasar code as most of later robot action tests were performed on hard coded sequences.

**Comment by cholan2100** [comment]
App based navigation for walking robot is not yet implemented for Ceasar code. As full walking stability was not fully tested due to Servo motor limitations. So all the motion tests were hard coded in the firmware(main.cpp).

**Comment by Rywokast** [comment]
wow... how did i not notice that >.> i had enabled the flags in the menuconfig but never thought to check if it was commented out haha.... well, its working now! now i just need to figure out how to switch on the relay
